language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - CI=true yarn test --passWithNoTests --ci
  - PUBLIC_URL=https://genesiskernel.github.io/genesis-front/ yarn build
before_deploy:
  - echo \{\"fullNodes\":[\"https://testnet0.apla.io:7079\",\"https://testnet1.apla.io:7079\",\"https://testnet2.apla.io:7079\"]\} > ./build/settings.json
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  github-token: $GITHUB_TOKEN
  on:
    branch: master