language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn install
  - CI=true yarn test --passWithNoTests --ci
  - REACT_APP_API_URL=159.65.200.225:7001 yarn build